name: Remote Trigger

on:
  repository_dispatch:
    types: [run-solar-system-tests]

jobs:
  run-tests:
    name: Run Tests from Remote Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
