name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

env:
  MONGO_URI: ${{ vars.MONGO_URI }}
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
    
jobs:
    unit-testing:
        name: Unit Testing
        strategy:
          matrix:
            node-version: [18, 19, 20]
            operating-system: [ubuntu-latest, windows-latest]
            exclude:
              - node-version: 20
                operating-system: windows-latest

        runs-on: ${{ matrix.operating-system }}
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
        
        - name: Ensure .npm directory exists
          run: mkdir -p ~/.npm

        - name: Cache Node Modules
          uses: actions/cache@v4
          with:
            path: ~/.npm
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          id: run-tests
          run: npm test
          
        - name: Archive Test Result
          if: failure() && steps.run-tests.outcome == 'failure' || steps.run-tests.outcome == 'success'
          uses: actions/upload-artifact@v4
          with:
            name: Mocha-Test-Result-${{ matrix.node-version }}-${{ matrix.operating-system }}
            path: test-results.xml
    
    code-coverage:
        name: Code Coverage
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v3
          with:
            node-version: 20

        - name: Install Dependencies
          run: npm install

        - name: Run Code Coverage
          continue-on-error: true
          run: npm run coverage

        - name: Archive Coverage Report
          uses: actions/upload-artifact@v4
          with:
            name: Code-Coverage-Report
            path: coverage
            retention-days: 7